 <nav>
            <ul>
                <li><a href="index.php">Html og CSS</a></li>
                <li><a href="internet.php">Internettets historie</a></li>
                <li><a href="kommunikation.php">Kommunikation</a></li>
                <li><a href="illustratorogphotoshop.php">Illustrator og Photoshop</a></li>
                <li><a href="versionsstyring.php">Versionsstyring</a></li>
                <li><a href="brugertests.php">Brugertest</a></li>
                <li><a href="farver.php">Farveteori</a></li>
                <li><a href="typografi.php">Typografi</a></li>
                <li><a href="tekstproduktion.php">Tekstproduktion</a></li>
                <li><a href="gestalt.php">Gestalt lovene</a></li>
                <li><a href="businessmodelcanvas.php">Business model canvas BMC</a></li>
                <li><a href="informationsarkitektur.php">Informationsarkitektur</a></li>
                <li><a href="ophavsretoglicens.php">Ophavsret og licens</a></li>
                <li><a href=""></a></li>
            </ul>
        </nav>